name: pred-knee-replacement-oai

dependencies:
    - python=3.12
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - matplotlib
    - pytorch
    - torchvision
    - h5py
    - wandb
    - pip
    - conda-forge::simpleitk
    - conda-forge::nibabel
    - seaborn
    - plotly
    - pip:
        - monai
        - segmentation-models-pytorch-3d
        - kaleido
