name: environment.yml

dependencies:
    - python=3.12
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - matplotlib
    - torch
    - monai 
    - wandb
    - pip
    - pip:
        - monai
