wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: 3D UNet
kernel_num:
  desc: null
  value: 16
dataset:
  desc: null
  value: IWOAI
epochs:
  desc: null
  value: 40
threshold:
  desc: null
  value: 0.5
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722257804.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.12.3
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
